# Generated by Django 3.2.22 on 2023-11-05 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='information',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='information',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='information',
            name='start_date',
            field=models.DateField(),
        ),
    ]
