# Generated by Django 3.2.22 on 2023-11-05 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20231105_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'ordering': ['end_date']},
        ),
    ]
