# Generated by Django 3.2.22 on 2023-11-06 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_alter_information_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='user',
            new_name='owner',
        ),
    ]
